BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Article" (
	"ID"	INTEGER,
	"Title"	TEXT,
	"Subject"	TEXT,
	"Section"	INTEGER,
	PRIMARY KEY("ID"),
	FOREIGN KEY("Section") REFERENCES "Section"("ID")
);
CREATE TABLE IF NOT EXISTS "Log" (
	"N"	INTEGER DEFAULT 0,
	"Article"	INTEGER,
	"Data"	BLOB,
	FOREIGN KEY("Article") REFERENCES "Article"("ID")
);
CREATE TABLE IF NOT EXISTS "Section" (
	"ID"	INTEGER,
	"Name"	TEXT UNIQUE,
	"Descriptions"	TEXT,
	PRIMARY KEY("ID")
);
COMMIT;
